a <-  read.table("household_power_consumption.txt", sep = ";")
a$V1 <- as.Date(as.character(a$V1),'%d/%m/%Y')
c <- subset(a,as.Date(V1) >= '2007-02-01' &  as.Date(V1) <= '2007-02-02')
d <- c
d <- transform(d, timestamp=as.POSIXct(paste(V1, V2)), "%d/%m/%Y %H:%M:%S")
d$V3 <- as.numeric(as.character(c$V3))
d$V4 <- as.numeric(as.character(c$V4))
d$V5 <- as.numeric(as.character(c$V5))
d$V7 <- as.numeric(as.character(c$V7))
d$V8 <- as.numeric(as.character(c$V8))
d$V9 <- as.numeric(as.character(c$V9))

png('plot4.png')
par(mfrow=c(2,2))
plot(d$timestamp,d$V3,type="l",xlab="", ylab="Global Active Power (kilowatts)")
plot(d$timestamp,d$V5,type="l",xlab="datetime", ylab="Voltage")
plot(d$timestamp,d$V7, type="l", xlab="", ylab="Energy sub metering")
lines(d$timestamp,d$V8,col="red")
lines(d$timestamp,d$V9,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
plot(d$timestamp,d$V4,type="l",xlab="datetime", ylab="Global_reactive_power")
dev.off()
