a <-  read.table("household_power_consumption.txt", sep = ";")
a$V1 <- as.Date(as.character(a$V1),'%d/%m/%Y')
c <- subset(a,as.Date(V1) >= '2007-02-01' &  as.Date(V1) <= '2007-02-02')
d <- c
d$V7 <- as.numeric(as.character(c$V7))
d$V8 <- as.numeric(as.character(c$V8))
d$V9 <- as.numeric(as.character(c$V9))
d <- transform(d, timestamp=as.POSIXct(paste(V1, V2)), "%d/%m/%Y %H:%M:%S")
png('plot3.png')
plot(d$timestamp,d$V7, type="l", xlab="", ylab="Energy sub metering")
lines(d$timestamp,d$V8,col="red")
lines(d$timestamp,d$V9,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.off()